spring.application.name=helloworld
server.port=8080

#spring.datasource.url=jdbc:h2:mem:tododb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=admin
#spring.datasource.password=1234

#spring.h2.console.enabled=true
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update

#postgresql db connection
spring.datasource.url=jdbc:postgresql://localhost:5432/tododb
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-ame=org.postgresql.Driver

#jpa/hibernate configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

#Set username and password to access the webpage
#spring.security.user.name=admin
#spring.security.user.password=1234


